---
languages:
  JavaScript: true
  Python: true
exclude_paths:
- "frontend/tests/*"
- "frontend/source/js/vendor/*"
- "frontend/source/style/libs/*"
- "styleguide/static/styleguide/vendor/*"
- "**/migrations/*"
- "**/vendor/*"
engines:
  eslint:
    enabled: true
    channel: "eslint-2"
    checks:
      import/no-unresolved:
        enabled: false
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
